[tool.poetry]
name = "stormlock"
version = "0.1.0"
description = "Simple distributed lock with support for multiple backends"
authors = ["Thayne McCombs <astrothayne@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
etcd3 = { version = "^0.12.0", optional = true }
redis = { version = "^3.4.1", optional = true }
boto3 = { version = "^1.13.1", optional = true }
psycopg2 = { version = "^2.8.5", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.extras]
etcd = ["etcd3"]
redis = ["redis"]
dynamodb = ["boto3"]
postgresql = ["psycopg2"]

[tool.poetry.plugins."stormlock.backends"]
"etcd" = "stormlock.backends.etcd:Etcd [etcd]"
"redis" = "stormlock.backends.redis:Redis [redis]"
"dynamodb" = "stormlock.backends.dynamodb:DynamoDB [dynamodb]"
"postgresql" = "stormlock.backends.postgresql:Postgresql [postgresql]"

[tool.poetry.scripts]
stormlock = "stormlock.cli:run"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
user_parentheses = true
line_length = 88

[tool.pylint.messages_control]
disable = "C0330, C0326, W0511"

[tool.pylint.format]
max-line-length = "88"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
