name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: actions/actions-poetry@v1.5.0
        with:
          python_version: 3.8.3
          poetry_version: 1.0.9
          args: install -E etcd -E redis -E dynamodb -E postgresql
      - uses: ricardochaves/python-lint@v1.1.0
        with:
          python-root-list: stormlock
