name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: 
          python-version: '3.8'
      - name: Install
        run: |
          pip install poetry 
          poetry install -E etcd -E redis -E dynamodb -E postgresql
          poetry run pip install mypy pylint isort
      - uses: psf/black@stable
      - name: Lint
        run: |
          poetry run mypy .
          poetry run pylint stormlock
          poetry run isort **/*.py -c

